# This file is copied into the user's config directory when they add this
# keyboard. Define any Kconfig options users may frequently want to set here.

# The Primer79 has 2 rotary encoders -- this is required for them to work.
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment to enable the display
# CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
